In [ ]:
#Q1 - What are the benefits of the built-in array package, if any?
#Answer:
Here are some advantages of using the array package:
- Compact Memory Usage
- Efficient Numeric Operations
- Faster Access and Manipulation
- Interoperability with C
- Serialized I/O Operations
- Type Enforcement

In [ ]:
#Q2 - What are some of the array package's limitations?
#Answer:
Here are some of its limitations:
- Fixed Size
- Single Data Type
- Limited Functionality
- Lack of High-level Operations
- Limited Flexibility

In [ ]:
#Q3 - Describe the main differences between the array and numpy packages.
#Answer:
Here are few differences:
- The numpy package is a powerful numerical computing library that provides a wide range of advanced functions and capabilities for working 
with multi-dimensional arrays, mathematical operations, linear algebra, random number generation, and more.

On the other hand, the array package is a built-in Python module that provides a basic array data structure with limited functionality focused 
primarily on storage and retrieval of numeric data.

- numpy arrays are more versatile and feature-rich than arrays created with the array package. numpy arrays support a wide range of operations, 
including advanced indexing, slicing, element-wise arithmetic operations, broadcasting, array reshaping, and aggregations. array objects, 
in comparison, have more limited functionality and lack many of the advanced array operations provided by numpy.

- numpy is known for its optimized and efficient implementation of array operations. It utilizes low-level languages like C and Fortran, 
as well as optimized algorithms, which can provide significant performance improvements compared to using plain Python lists or 
the array package. numpy also has built-in support for vectorized operations, which allows for efficient element-wise computations on arrays.

- numpy arrays allow for storing elements of different data types within the same array. This flexibility enables handling diverse data types 
in a single data structure. In contrast, array objects require all elements to have the same data type.

In [ ]:
#Q4 - Explain the distinctions between the empty, ones, and zeros functions.
#Answer:
1. numpy.empty(shape, dtype=float, order='C'):
- This function creates a new array without initializing its elements to any specific values.
- It takes the shape parameter, which specifies the dimensions (or shape) of the array as a tuple. For example, shape=(2, 3) creates a 
2-dimensional array with 2 rows and 3 columns.
- The optional dtype parameter specifies the data type of the array elements. By default, it is set to float. You can specify other data types 
like int, bool, complex, etc.
- The optional order parameter specifies the memory layout of the array. By default, it is set to 'C', which means row-major order. 
Alternatively, you can set it to 'F' for column-major order.


2. numpy.ones(shape, dtype=None, order='C'):

- This function creates a new array filled with ones.
- It takes the shape parameter, which specifies the dimensions of the array as a tuple, similar to numpy.empty.
- The optional dtype parameter specifies the data type of the array elements. If not provided, it defaults to float.
- The optional order parameter specifies the memory layout of the array, similar to numpy.empty.

3. numpy.zeros(shape, dtype=None, order='C'):

- This function creates a new array filled with zeros.
- It takes the shape parameter, specifying the dimensions of the array as a tuple, similar to numpy.empty.
- The optional dtype parameter specifies the data type of the array elements. If not provided, it defaults to float.
- The optional order parameter specifies the memory layout of the array, similar to numpy.empty

In [ ]:
#Q5 - In the fromfunction function, which is used to construct new arrays, what is the role of the callable argument?
#Answer:
In the numpy.fromfunction function, the callable argument plays a crucial role in constructing new arrays based on a user-defined function. 
The callable is a function or a callable object that defines the values of the elements in the array being created.

The callable function receives as input the indices of the array elements and returns the corresponding values. The indices are determined 
by the shape of the array being created. The function is called with a tuple of indices, where each element of the tuple represents 
the index along a specific dimension.

In [ ]:
#Q6 - What happens when a numpy array is combined with a single-value operand (a scalar, such as
#an int or a floating-point value) through addition, as in the expression A + n?

#Answer:
When a NumPy array A is combined with a single-value operand (n) through addition (+), NumPy performs an element-wise addition operation 
between the array and the scalar value.

The scalar value n is broadcasted to match the shape of the array A, and then the addition operation is performed element by element. 
Each element in the array A is added with the scalar value n, resulting in a new array with the same shape as A.

In [ ]:
#Q7 - Can array-to-scalar operations use combined operation-assign operators (such as += or *=)? What is the outcome?
#Answer:
No, array-to-scalar operations cannot use combined operation-assign operators like += or *=. These operators are designed for in-place 
modification of arrays, but when used with a scalar value, they would modify the array elements in an undefined manner.

When the combined operation-assign operators are used with a scalar operand, they assume that the target variable is an array and perform 
the operation element-wise on the array. However, when used with a scalar value, there is no well-defined behavior for modifying individual 
elements of a scalar.

In [ ]:
#Q8 - Does a numpy array contain fixed-length strings? What happens if you allocate a longer string to one of these arrays?
#Answer:
Yes, a NumPy array can contain fixed-length strings. You can create a NumPy array with a specific data type, such as numpy.dtype('S10'), 
which represents fixed-length strings of length 10.

If you allocate a longer string to an array with fixed-length strings, NumPy will truncate the string to fit the specified length. No error or 
warning will be raised. The string will be truncated from the right, removing any characters beyond the specified length.

In [2]:
#Q9 - What happens when you combine two numpy arrays using an operation like addition (+) or
#multiplication (*)? What are the conditions for combining two numpy arrays?

#Answer:
'''When you combine two NumPy arrays using the addition (+) or multiplication (*) operators, NumPy performs element-wise operations between 
the corresponding elements of the arrays. The resulting array will have the same shape as the input arrays, and each element of the 
output array will be the result of the corresponding element-wise operation.

To combine two NumPy arrays using the addition or multiplication operators, the following conditions must be satisfied:

- The arrays must have the same shape. The shape refers to the dimensions of the arrays, such as the number of rows and columns for 
2-dimensional arrays.

- The arrays must have compatible data types. NumPy arrays have a specified data type for their elements, such as int, float, or bool. 
The data types of the two arrays being combined must be compatible for the given operation.'''

#exp:
import numpy as np

A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

# Addition
result_add = A + B
print(result_add)

# Multiplication
result_mul = A * B
print(result_mul)

[5 7 9]
[ 4 10 18]


In [5]:
#Q10: What is the best way to use a Boolean array to mask another array?
#Answer:
'''The best way to use a Boolean array to mask another array in NumPy is by using Boolean indexing. Boolean indexing allows you to select 
elements from an array based on a corresponding Boolean mask, where the mask determines which elements to include or exclude.'''

#exp:
import numpy as np

# Original array
arr = np.array([1, 2, 3, 4, 5])

# Boolean mask
mask = np.array([True, False, True, False, True])

# Masking the original array
masked_arr = arr[mask]

print(masked_arr)



[1 3 5]


In [ ]:
#Q11 - What are three different ways to get the standard deviation of a wide collection of data using
#both standard Python and its packages? Sort the three of them by how quickly they execute.

#Answer:
Sorting the three different ways to calculate the standard deviation of a wide collection of data in Python based on their execution speed, 
from fastest to slowest:

NumPy: Using the numpy package is typically the fastest approach for calculating the standard deviation of large collections of data. 
The numpy library provides the numpy.std() function, which can directly calculate the standard deviation of an array or list of values.

Pandas: If your data is in a tabular format or DataFrame, using the pandas library can be an efficient way to calculate the standard deviation. 
The pandas library provides the DataFrame.std() method, which computes the standard deviation along each column or row of the DataFrame.

Standard Python: Using standard Python without any additional packages, you can calculate the standard deviation using mathematical formulas. 
However, this approach is typically slower compared to using specialized libraries like NumPy or pandas, especially for large datasets.

In [9]:
#Q12 - What is the dimensionality of a Boolean mask-generated array?
#Answer:
'''The dimensionality of a Boolean mask-generated array depends on the shape of the Boolean mask itself.

When you use a Boolean mask to index an array, the resulting array will have the same number of dimensions as the Boolean mask. 
The shape of the resulting array will be determined by the True values in the mask.'''

#Exp:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

mask = np.array([[True, False, True],
                 [False, True, False],
                 [True, False, True]])
